signup:
  enabled: false

anonymous_browsing:
  enabled: false

oauth:
  local_login:
    enabled: true

delete:
  enabled: true
  garbage_collector:
    enabled: true

background:
  sync:
    strategy: update
