version: '3'

services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest@sha256:90546cbd843c61cf34e43df3f2eecc24a76950641c734c30373a2d4190ad4abb
    container_name: cloudflare-ddns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config.json:/config.json
