version: '3'

services:
  arora_api:
    build: .
    env_file: .arora_api.env
    command: db_arora_api_backup
    volumes:
      - ./password:/opt/app/password
      - /storage/backups:/storage/backups
    networks:
      - arora_api_production_default

  arora_discord:
    build: .
    env_file: .arora_discord.env
    command: db_arora_discord_backup
    volumes:
      - ./password:/opt/app/password
      - /storage/backups:/storage/backups
    networks:
      - arora_discord_production_default

networks:
  arora_api_production_default:
    external: true
  arora_discord_production_default:
    external: true
