pihole:
  # -- Configuration for the DNS service on port 53
  serviceDns:
    # -- deploys a mixed (TCP + UDP) Service instead of separate ones
    mixedService: true

    # -- `spec.type` for the DNS Service
    type: LoadBalancer

    # -- Annotations for the DNS service
    annotations:
      "io.cilium/lb-ipam-sharing-key": "pihole"
      "io.cilium/lb-ipam-ips": "192.168.31.25"


  # -- Configuration for the DHCP service on port 67
  serviceDhcp:
    # -- Generate a Service resource for DHCP traffic
    enabled: false

  # -- Configuration for the web interface service
  serviceWeb:
    # -- `spec.type` for the web interface Service
    type: LoadBalancer

    # -- Annotations for the DHCP service
    annotations:
      "io.cilium/lb-ipam-sharing-key": "pihole"
      "io.cilium/lb-ipam-ips": "192.168.31.26"
