version: '3'

services:
  app:
    image: jasonwhite0/rudolfs:0.3.5
    volumes:
      - data:/data
      - ./lfs-storage:/lfs-storage
    restart: unless-stopped
    entrypoint:
      - /tini
      - --
      - /rudolfs
      - --cache-dir
      - /data
      - --key
      - $LFS_ENCRYPTION_KEY
      - --max-cache-size
      - $LFS_MAX_CACHE_SIZE
      - local
      - --path
      - /lfs-storage
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.rudolfs.rule=Host(`$HOST`) && PathPrefix(`/api`)
      - traefik.http.middlewares.rudolfs.forwardauth.address=https://$HOST/auth
      - traefik.http.routers.rudolfs.middlewares=rudolfs-auth@docker,rewrite-body-authenticated@file
      - traefik.http.routers.rudolfs.tls.certresolver=default

volumes:
  data: