version: '3'

services:
  traefik:
    image: traefik:2.2
    container_name: traefik
    restart: unless-stopped
    networks:
      - default
      - nsadmin-api_default
      - docker_registry_default
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - ./dynamic:/dynamic/

networks:
  nsadmin-api_default:
    external: true
  docker_registry_default:
    external: true
