version: '3'

services:
  traefik:
    image: traefik:2.5.4
    container_name: traefik
    restart: unless-stopped
    env_file: .env
    networks:
      - default
      - harbor_harbor
      - arora_api_production_default
      - arora_api_staging_default
      - trello_discord_webhook_production_default
      - sharex_default
      - rudolfs_default
      - rudolfs_auth_default
      - pihole_default
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
      - '853:853'
      - '53:53/udp'
      - '53:53'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - ./dynamic:/dynamic/

networks:
  harbor_harbor:
    external: true
  arora_api_production_default:
    external: true
  arora_api_staging_default:
    external: true
  trello_discord_webhook_production_default:
    external: true
  sharex_default:
    external: true
  rudolfs_default:
    external: true
  rudolfs_auth_default:
    external: true
  pihole_default:
    external: true
