entryPoints:
  http:
    address: :80
  https:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - <ip>
#  dnsovertls:
#    address: :853
#  dns:
#    address: :53
#  udpdns:
#    address: :53/udp

providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false
  file:
    directory: dynamic/

api:
  dashboard: true
  debug: true

pilot:
  token: <token>

experimental:
  plugins:
    plugin-rewritebody:
      moduleName: github.com/traefik/plugin-rewritebody
      version: v0.3.1

log:
  level: DEBUG

certificatesResolvers:
  default:
    acme:
      email: <email>
      storage: acme.json
      httpChallenge:
        entryPoint: http
