version: '3'

services:
  db:
    image: postgres:11.2@sha256:3eda284d1840c21b3b54a10aab80233cf82b93236e70603bdd097088932f6ba0
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: nextcloud:23.0.0@sha256:39ed3b1633723b4923e006e7a89144c093f1dc07413047cc1bbe9ffacafeb30b
    restart: unless-stopped
    env_file: .env
    hostname: maya
    volumes:
      - nextcloud_data:/var/www/html
      - /storage/nextcloud:/var/www/html/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`$HOST`)
      - traefik.http.routers.nextcloud.middlewares=sts@file
      - traefik.http.routers.nextcloud.tls.certresolver=default

  cron:
    image: rcdailey/nextcloud-cronjob:latest@sha256:456848d06fe6d967c1480810200bcc75c7f12410b98708d2333b4bfe693dd70e
    restart: unless-stopped
    network_mode: none
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NEXTCLOUD_CONTAINER_NAME=app
      - NEXTCLOUD_PROJECT_NAME=nextcloud

  onlyoffice:
    image: onlyoffice/documentserver:7.0.0.132@sha256:32d7833c15135fc80cbf573cc055e851719b05d5a8d1479f66bfbbbf97207059
    restart: unless-stopped
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      - ./onlyoffice/data:/var/www/onlyoffice/Data
      - ./onlyoffice/db:/var/lib/postgresql
    labels:
      - traefik.enable=true
      - traefik.http.routers.onlyoffice.rule=Host(`$HOST`) && PathPrefix(`/onlyoffice`)
      - traefik.http.routers.onlyoffice.tls.certresolver=default

      # Headers for OnlyOffice, https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/151
      - traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers
      - traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowOrigin=*

volumes:
  nextcloud_data:
  postgres_data:
