http:
  middlewares:
    sts:
      headers:
        frameDeny: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        browserXssFilter: true

    api-strip:
      stripPrefix:
        prefixes:
          - /api

    rewrite-body-authenticated:
      plugin:
        plugin-rewritebody:
          lastModified: true
          rewrites:
            - regex: '"authenticated": true'
              replacement: '"authenticated": false'
