on:
  push:
  workflow_dispatch:

jobs:
  helm_install:
    name: Helm install Traefik
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.11.1

      - name: Create kubeconfig file
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod 644 ~/.kube/config

      - name: Helm install Traefik
        run: |
          helm upgrade traefik traefik --atomic --dependency-update -f traefik/values.yaml -n traefik
