on:
  push:
    branches:
      - main
    paths:
      - cert-manager/**
  workflow_dispatch:

jobs:
  helm_install:
    name: Helm install cert-manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.11.1

      - name: Create kubeconfig file
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod go-r ~/.kube/config

      - name: Helm install cert-manager
        run: |
          helm upgrade cert-manager cert-manager \
            --atomic \
            --dependency-update \
            --skip-schema-validation \
            -n cert-manager \
            -f cert-manager/values.yaml \
            --set "cert-manager.acmeEmail=$ACME_EMAIL"
        env:
          ACME_EMAIL: ${{ secrets.CERT_MANAGER_ACME_EMAIL }}
