on:
  push:
  workflow_dispatch:

jobs:
  helm_install:
    name: Helm install Traefik
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.11.1

      - name: Create kubeconfig file
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config

      - name: Helm install Traefik
        run: |
          helm repo add traefik https://traefik.github.io/charts
          helm upgrade traefik traefik/traefik --atomic --version v23.0.1 -f traefik/values.yaml -n traefik
          