on:
  push:
    branches:
      - main
    paths:
      - traefik/**
  workflow_dispatch:

jobs:
  helm_install:
    name: Helm install Traefik
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.18.6

      - name: Create kubeconfig file
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod go-r ~/.kube/config

      - name: Mask Traefik URLs
        run: |
          while IFS= read -r URL; do
            echo '::add-mask::'"$URL"
          done < <(echo "$TRAEFIK_URLS" | jq -r '.[]')
        env:
          TRAEFIK_URLS: ${{ secrets.TRAEFIK_URLS }}

      - name: Get Traefik host
        id: get_host
        run: |
          URL="$(echo "$TRAEFIK_URLS" | jq -r '.traefik')"
          echo 'ingress_host='"$URL" >> "$GITHUB_OUTPUT"
        env:
          TRAEFIK_URLS: ${{ secrets.TRAEFIK_URLS }}

      - name: Get legacy URLs
        id: get_legacy_urls
        run: |
          RESULT=''
          while IFS= read -r URL; do
            if [ ! "$RESULT" ]; then
              RESULT="$URL"
              continue
            fi
            RESULT="$URL,$RESULT"
          done < <(echo "$TRAEFIK_LEGACY_URLS" | jq -r '.[]')
          echo 'legacy_urls='"$RESULT" >> "$GITHUB_OUTPUT"
        env:
          TRAEFIK_LEGACY_URLS: ${{ secrets.TRAEFIK_LEGACY_URLS }}

      - name: Helm install Traefik
        run: |
          helm upgrade traefik traefik \
            --atomic \
            --dependency-update \
            -n traefik \
            -f traefik/values.yaml \
            --set "traefik.ingressRoute.dashboard.matchRule=Host(\`$INGRESS_HOST\`) && (PathPrefix(\`/dashboard\`) || PathPrefix(\`/api\`))" \
            --set "traefik.certificatesResolvers.letsencrypt.acme.email=$ACME_EMAIL" \
            --set "traefik.ingressHost=$INGRESS_HOST" \
            --set "traefik.legacyUrls={$LEGACY_URLS}"
        env:
          INGRESS_HOST: ${{ steps.get_host.outputs.ingress_host }}
          ACME_EMAIL: ${{ secrets.TRAEFIK_ACME_EMAIL }}
          LEGACY_URLS: ${{ steps.get_legacy_urls.outputs.legacy_urls }}
